_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 30
                - 41
                - 49
                - 51
                - 53
            "2":
                - 1
                - 2
                - 3
                - 5
                - 30
                - 41
                - 49
                - 51
                - 53
            "3":
                - 13
                - 55
                - 61
            "4": 3.10.18
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
